spring:
  application:
    name: greenhouse
  profiles:
    default: local
  datasource:
    username: greenhouse_app
  flyway:
    schemas: greenhouse
    default-schema: greenhouse
    create-schemas: false

greenhouse:
  esp32:
    base-url: ${ESP32_BASE_URL:http://192.168.18.26}
    pins:
      led: 32
      fan: 26
      pump: 25

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8081
