spring:
  datasource:
    url: jdbc:postgresql://db:5432/house_control
    password: ${GREENHOUSE_DB_PASSWORD:greenhouse_app}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/house-control}
